### ISSUE TITLE
В Каталоге при уменьшении кол-ва элементов до 0 не происходит удаления из корзины

### ISSUE THREAD

**Issue by MiWas13** [MiWas13/YaPracticumSprint13Coh05#2]
Продукт остаётся "в корзине", но с кол-вом 0. Продукт должен переходить в состояние "не выбранный", должна отображаться кнопка "в корзину"
![image](https://github.com/MiWas13/YaPracticumSprint13Coh05/assets/18617783/f97f898c-7af8-4787-9b5b-175576505fe0)

**Comment by avkochekov** [comment]
Great bug! Thank you!
