### ISSUE TITLE
Заголовок в тулбаре не меняется при переходе на вкладку корзина

### ISSUE THREAD

**Issue by MiWas13** [MiWas13/YaPracticumSprint13Coh05#3]
Заголовок в тулбаре должен соответствовать названию выбранной вкладки: "Каталог" или "Корзина"

![image](https://github.com/MiWas13/YaPracticumSprint13Coh05/assets/18617783/392aa500-9048-469e-9767-9dda9588453f)

**Comment by artwist-polyakov** [comment]
Fixed ✅
